version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - er-net
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    networks:
      - er-net
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data:/data/db"
    networks:
      - er-net
  elasticsearch:
    image: elasticsearch:8.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 设置Java内存限制
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200"
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"  # 数据持久化
    networks:
      - er-net

networks:
  er-net:
    name: ERChat_net