server:
  port: 18081
spring:
  application:
    name: designer-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.128:8848
logging:
  level:
    com.erchat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"