server:
  port: 18081
spring:
  application:
    name: designer-service
  profiles:
    active: dev
logging:
  level:
    com.erchat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"