server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: erchat-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.128:8848
    gateway:
      routes: # 路由配置
        - id: diagram_route
          uri: lb://diagram-service
          predicates:
            - Path=/diagram/**
        - id: project_route
          uri: lb://project-service
          predicates:
            - Path=/project/**


erchat:
  jwt:
    location: classpath:erchat.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /**