server:
  port: 18082
spring:
  application:
    name: project-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.128:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.204.128:3306/erchat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
logging:
  level:
    com.erchat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"